
rootProject.name = "learning-kotlin"

include(":common")
include(":chap01")
include(":chap02")
include(":chap03")
include(":chap04")
include(":chap05")
include(":chap06")
include(":chap07")
include(":chap08")
include(":chap09")
include(":chap10")
include(":cobt01")
include(":cobt02")
include(":cobt03")
include(":cobt04")
include(":cobt05")
include(":cobt06")
include(":cobt07")
include(":cobt08")
include(":cobt09")
include(":cobt10")
include(":cobt11")
include(":cobt12")
include(":cobt13")
include(":cobt14")
include(":cobt15")
include(":cobt16")
include(":cobt17")
include(":cobt18")
include(":cjoy10")
include(":cjoy11")
include(":cjoy15")
include(":cjoy16")
